dataset:
  dataset_name: NovelQA                                 # or InfiniteQALoader, NovelQA,InfiniteChoice
  dataset_path: ./data/NovelQA # path to your dataset path. 
  # or NovelQA: ./data/NovelQA
  # or InfiniteQALoader: ./data/InfiniteBench/longbook_qa_eng.jsonl   ./data/InfiniteBench/longbook_choice_eng.jsonl

llm:
  llm_name: Meta-Llama-3.1-8B-Instruct         #Llama-3.1-8B-Instruct
  llm_path: path/to/your/llm/model     # /home/rag/Meta-Llama-3.1-8B-Instruct  # path to your llm model.
  llm_device: cuda               # device to run the llm.

paths:
  log_path: ./log             # path to save the log.
  answer_path: ./answer/test  # path to save the answer. no need to identify the dataset, they will be automatically saved in corresponding folder.
  cache_path: ./cache/test     # path to save the cache.

extractor:
  language: "en"  # language of the extractor.
  method: "Spacy" # method of the extractor.

cluster:
  length: 1200  # length of each chunk.
  overlap: 50  # overlap of each chunk.
  merge_num: 5  # number of chunks to merge.
  force_Reextract: False   # whether to force reextract the graph, ignoring the existed cache.

resume:
  resumeIndex: 0  # index of the resume.

retriever:
  kwargs:
    device: cuda                      # device to run the retriever.
    shortest_path_k: 4                # number of shortest path to retrieve. 
    debug: True                       # whether to print the debug information.
    merge_num: 5                      # number of chunks to merge.
    overlap: 50                      # overlap of each chunk.
    tokenizer: path/to/your/llm/tokenizer    # path to your tokenizer.
    max_chunk_setting: 25             # max number of chunks to retrieve.
    use_fusion: True                 # whether to use fusion retrieval (combines entity graph + summary tree)



